version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: ikehi-stores-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tobi_user
      POSTGRES_PASSWORD: tobi_password
      POSTGRES_DB: ecommerce1
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 